uploads = []
outputs = []

[[generated]]
id = "LwsrLcpSjrV65y2XViVyQ"
uri = "file://artifacts/his-altar-app/assets/images/icon.png"
type = "image"
title = "generated_image"

[[generated]]
id = "ZzdsoAcnxf2Lr1G0DWT9H"
uri = "file://artifacts/his-altar-app/assets/images/altar-splash.png"
type = "image"
title = "golden altar incense photorealistic"
