import { Router, type IRouter } from "express";
import healthRouter from "./health";
import { authRouter } from "./auth";
import { configRouter } from "./config";
import { altarReportsRouter } from "./altarReports";
import { dailyAltarReportsRouter } from "./dailyAltarReports";
import { workersRouter } from "./workers";
import { checkInsRouter } from "./checkIns";
import { serviceReportsRouter } from "./serviceReports";
import { serviceNotesRouter } from "./serviceNotes";
import { campusPasswordsRouter } from "./campusPasswords";
import { teamPresetsRouter } from "./teamPresets";
import { activityLogsRouter } from "./activityLogs";
import { dbancContactsRouter } from "./dbancContacts";
import { dbancCustomFieldsRouter } from "./dbancCustomFields";
import { pxpConfigRouter } from "./pxpConfig";
import { pxpCallLogsRouter } from "./pxpCallLogs";
import { pxpCallersRouter } from "./pxpCallers";
import { callerWebauthnRouter } from "./callerWebauthn";
import { orgsRouter } from "./orgs";
import { superadminRouter } from "./superadmin";
import { stripeRouter } from "./stripe";
import { webauthnRouter } from "./webauthn";
import { notificationsRouter } from "./notifications";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/auth", authRouter);
router.use("/config", configRouter);
router.use("/altar-reports", altarReportsRouter);
router.use("/daily-altar-reports", dailyAltarReportsRouter);
router.use("/workers", workersRouter);
router.use("/check-ins", checkInsRouter);
router.use("/service-reports", serviceReportsRouter);
router.use("/service-notes", serviceNotesRouter);
router.use("/campus-passwords", campusPasswordsRouter);
router.use("/team-presets", teamPresetsRouter);
router.use("/activity-logs", activityLogsRouter);
router.use("/dbanc/contacts", dbancContactsRouter);
router.use("/dbanc/custom-fields", dbancCustomFieldsRouter);
router.use("/pxp/config", pxpConfigRouter);
router.use("/pxp/call-logs", pxpCallLogsRouter);
router.use("/pxp/callers/webauthn", callerWebauthnRouter);
router.use("/pxp/callers", pxpCallersRouter);
router.use("/orgs", orgsRouter);
router.use("/superadmin", superadminRouter);
router.use("/stripe", stripeRouter);
router.use("/webauthn", webauthnRouter);
router.use("/notifications", notificationsRouter);

export default router;
